# Base image
FROM node:18

# Working directory
WORKDIR /apps

RUN git clone -b main https://github.com/yoju-lab/study_vues

# Copy package.json and package-lock.json
# COPY package*.json ./

# Install dependencies
# RUN npm init

# Copy the rest of the application code
# COPY . .

# Command to run the app
# CMD ["npm", "run", "dev"]
